config/routes.rb
Rails.application.routes.draw do
  resources :cases
  resources :referring_doctors
  resources :patients
  resources :items
  get 'users/index'
  post 'users/create'
  root 'cases#index'
  resources :user_roles
  resources :items
  resources :reports
  devise_for :users
  get 'user/:id', to: "users#toggle_activation", as: "toggle_activation"
  get 'items/activated_items', to: 'items#activated_items'
  post 'case/:id/end', to:'cases#end_case', as: "end_case"
  post 'case/:id/report', to:'cases#report_case', as: "reported_case"
  post 'case/:id/contact', to:'cases#contact_case', as: "contacted_case"
  put 'case/:id/items', to: 'cases#update_items', as: "update_case_items"
  put 'case/:id', to: 'cases#update', as: "update_case"


  get 'generate_reports', to: 'reports#generate_reports', as: "g_reports"
  get 'reports/result', to: 'reports#result', as: "reports_result"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user_role.rb
# == Schema Information
#
# Table name: user_roles
#
#  id         :bigint           not null, primary key
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class UserRole < ApplicationRecord
    has_many :users, class_name: "User", foreign_key: "user_role_id", dependent: :restrict_with_error
end

app/controllers/user_roles_controller.rb
class UserRolesController < ApplicationController
  before_action :set_user_role, only: %i[ show edit update destroy ]
  before_action :authorize_controller

  # GET /user_roles or /user_roles.json
  def index
    @user_roles = UserRole.all
  end

  # GET /user_roles/1 or /user_roles/1.json
  def show
  end

  # GET /user_roles/new
  def new
    @user_role = UserRole.new
  end

  # GET /user_roles/1/edit
  def edit
  end

  # POST /user_roles or /user_roles.json
  def create
    @user_role = UserRole.new(user_role_params)

    respond_to do |format|
      if @user_role.save
        format.html { redirect_to @user_role, notice: "User role was successfully created." }
        format.json { render :show, status: :created, location: @user_role }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user_role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_roles/1 or /user_roles/1.json
  def update
    respond_to do |format|
      if @user_role.update(user_role_params)
        format.html { redirect_to @user_role, notice: "User role was successfully updated." }
        format.json { render :show, status: :ok, location: @user_role }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user_role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_roles/1 or /user_roles/1.json
  def destroy
    @user_role.destroy
    respond_to do |format|
      format.html { redirect_to user_roles_url, notice: "User role was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_role
      @user_role = UserRole.find(params[:id])
    end

    def authorize_controller
      if !current_user.admin?
        redirect_to root_path
      end
    end

    # Only allow a list of trusted parameters through.
    def user_role_params
      params.fetch(:title, {})
    end
end

app/helpers/user_roles_helper.rb
module UserRolesHelper
end

app/views/user_roles/_form.html.erb
<%= form_with(model: user_role, local: true) do |form| %>
  <div class="form-group">
    <label for="title">Title</label>
    <%= form.text_field :title ,{:class => 'form-control'}%>
  </div>
  <% if user_role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_role.errors.count, "error") %> prohibited this user_role from being saved:</h2>
      
      <ul>
        <% user_role.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/user_roles/edit.html.erb
<h1>Editing User Role</h1>

<%= render 'form', user_role: @user_role %>

<%= link_to 'Show', @user_role %> |
<%= link_to 'Back', user_roles_path %>

app/views/user_roles/index.html.erb
<p id="notice"><%= notice %></p>
<div class="col-lg-12">
        	<div class="panel panel-default">
            <div class="panel-heading">
                <div class="row">
                <h3 class="col-10">User Roles</h3>
                <%= link_to 'New User Role', new_user_role_path, class: 'btn btn-success' %>
                </div>
            </div>
            <div class="panel-body">
<table class="table table-condensed" style="border-collapse:collapse;">

    <thead class="thead-light">
        <tr><th>&nbsp;</th>
            <th>Title</th>
            <th>Action</th>

        </tr>
    </thead>

    <tbody class="table-striped table-hover"> 
          <% for role in @user_roles %>        
          

        
        <tr>
            <td><button class="btn btn-default btn-xs"><span class="glyphicon glyphicon-eye-open"></span></button></td>
            <td><%= role.title %></td>
            
            <td><%= link_to 'Destroy', role, method: :delete, data: { confirm: 'Are you sure you want to delete this role?' } %></td>
          

        </tr>
  
        
        <% end %>
    </tbody>
    
</table>
            </div>
        
          </div> 
        
      </div>

app/views/user_roles/new.html.erb
<h1>New User Role</h1>

<%= render 'form', user_role: @user_role %>

<%= link_to 'Back', user_roles_path %>

app/views/user_roles/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_role_path(@user_role) %> |
<%= link_to 'Back', user_roles_path %>