config/routes.rb
Rails.application.routes.draw do
  resources :cases
  resources :referring_doctors
  resources :patients
  resources :items
  get 'users/index'
  post 'users/create'
  root 'cases#index'
  resources :user_roles
  resources :items
  resources :reports
  devise_for :users
  get 'user/:id', to: "users#toggle_activation", as: "toggle_activation"
  get 'items/activated_items', to: 'items#activated_items'
  post 'case/:id/end', to:'cases#end_case', as: "end_case"
  post 'case/:id/report', to:'cases#report_case', as: "reported_case"
  post 'case/:id/contact', to:'cases#contact_case', as: "contacted_case"
  put 'case/:id/items', to: 'cases#update_items', as: "update_case_items"
  put 'case/:id', to: 'cases#update', as: "update_case"


  get 'generate_reports', to: 'reports#generate_reports', as: "g_reports"
  get 'reports/result', to: 'reports#result', as: "reports_result"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/patient.rb
# == Schema Information
#
# Table name: patients
#
#  id         :bigint           not null, primary key
#  mobile     :string
#  name       :string
#  address    :text
#  email      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Patient < ApplicationRecord
    has_many :cases, class_name: "Case", foreign_key: "patient_id"
    validates_uniqueness_of :mobile, on: :create, message: "already exists"
end

app/controllers/patients_controller.rb
class PatientsController < InheritedResources::Base
  before_action :authorize_controller
  before_action :authenticate_user!

  def index
    @q = Patient.ransack(params[:q])
    @patients = @q.result.page(params[:page]).per(10)
  end
  
  def show
    @patient = Patient.find(params[:id])
  end
  
  private

    def patient_params
      params.require(:patient).permit(:mobile, :name, :address, :email)
    end

    def authorize_controller
      if !current_user.admin? && !current_user.accounting? && !current_user.secertary?
        redirect_to root_path
      end
    end

end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_form.html.erb
<%= form_with(model: patient, local: true) do |form| %>
  <% if patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
        <% patient.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  
  
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, {:class => 'form-control', :required => true} %>
  </div>
  <div class="form-group">
    <%= form.label :mobile %>
    <%= form.text_field :mobile, {:class => 'form-control', :required => true} %>
  </div>

  <div class="form-group">
    <%= form.label :address %>
    <%= form.text_area :address, {:class => 'form-control'} %>
  </div>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, {:class => 'form-control'} %>
  </div>

  <div class="actions">
    <%= form.submit 'Add Patient', :class => 'mt-2 btn btn-primary' %>
  </div>
<% end %>

app/views/patients/edit.html.erb
<%= link_to  patients_path do%>
  <i class="material-icons">arrow_back</i>
<%end %>
<h1>Editing Patient</h1>

<%= render 'form', patient: @patient %>

app/views/patients/index.html.erb
<p id="notice"><%= notice %></p>
<div class="col-lg-12">
  <div class="panel panel-default">
    <div class="panel-heading">
      <div class="row">
        <h3 class="col-10">Patients</h3>
        <div class="col-2">
        <button  class='btn btn-success' style="border-radius: 50%;line-height: 0px;color:white"><a style="color:white;" href=<%=new_patient_path%>><i class="material-icons">add</i></a></button>
        <button type="button" class="btn btn-warning" style="border-radius:50%;line-height:0;" data-toggle="modal" data-target="#filterModel"><i class="material-icons">filter_list</i></button>
        </div>
      </div>
    </div>
    <div class="panel-body">
      <table class="table table-condensed" style="border-collapse:collapse;">
        <thead >
          <tr>
            <th>Mobile</th>
            <th>Name</th>
            <th>Address</th>
            <th>Email</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody class="table-striped table-hover">
          <% @patients.each do |patient| %>
            <tr>
              <td><%= patient.mobile %></td>
              <td><%= patient.name %></td>
              <td><%= patient.address %></td>
              <td><%= patient.email %></td>
              <td><%= link_to patient_path(patient) do %>
                  <i class="material-icons">visibility</i>
                <%end  %>
              </td>
              <td><%= link_to edit_patient_path(patient) do %>
                  <i class="material-icons">edit</i>
                <%end %>
              </td>
              <td><%= link_to patient, method: :delete, data: { confirm: 'Are you sure?' } do %>
                  <i class="material-icons">delete</i>
                <%end  %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row justify-content-end">
  <%= paginate @patients %>
  </div>
</div>
<div class="modal fade" id="filterModel" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h2>Filter Patients</h2>
      </div>
      <div class="modal-body">
        <%= search_form_for @q do |f| %>
        <div align="end">
        <%= link_to "Reset", request.path, class:"cancel-button" %>
        </div>
          <div class="form-group">
            <%= f.label :name_cont %>
            <%= f.search_field :name_cont, {:class => 'form-control'} %>
          </div>
          <div class="form-group">
            <%= f.label :mobile_cont %>
            <%= f.search_field :mobile_cont, {:class => 'form-control'} %>
          </div>
          <div class="form-group">
            <%= f.label :email_cont %>
            <%= f.search_field :email_cont, {:class => 'form-control'} %>
          </div>
          <%= f.submit "Search", :class => "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/patients/new.html.erb
<%= link_to  patients_path do%>
  <i class="material-icons">arrow_back</i>
<%end %>
<h1>New Patient</h1>

<%= render 'form', patient: @patient %>

app/views/patients/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <%= link_to  patients_path do%>
    <i class="material-icons">arrow_back</i>
  <%end %>
  <br>
  <h2>
    <%= @patient.name %>
  </h2>
  <p>
    <strong>Mobile:</strong>
    <%= @patient.mobile %>
  </p>
  <p>
    <strong>Address:</strong>
    <%= @patient.address %>
  </p>
  <p>
    <strong>Email:</strong>
    <%= @patient.email %>
  </p>
  <hr/>
  <div class="container">
    <div class="row">
      <div class="col-10">
        <h3>Cases</h3>
      </div>
      <div class="col-2">
        <button type="button" class="btn btn-success" data-toggle="modal" data-target="#addCaseModel">New Case</button>
      </div>
    </div>
    <hr>
    <div>
      <div class="list-group">
        <%@patient.cases.order("created_at DESC").each do |patient_case| %>
          <a href="<%=case_path(patient_case)%>" class="list-group-item list-group-item-action">
          <p>Case Number : <%= patient_case.id %>  - Created At: <%= patient_case.created_at %></p>
        </a>
      <%end %>
    </div>
  </div>
  <div class="modal fade" id="addCaseModel" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <p id="notice"><%= notice %></p>
          <h5 class="modal-title" id="exampleModalLabel">Add a new Case</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <%= form_with url: "/cases", method: :post do  |form| %>
            <div class="form-group">
              <label for="note">Note</label>
              <textarea  name="note" class="form-control"></textarea>
            </div>
            <div class="form-group">
              <label for="image">Image</label>
              <%= form.file_field :image, :class => "form-control" %>
            </div>
            <div class="form-group">
              <label for="referring_doctor_id">Referring doctor</label>
              <%= select_tag "referring_doctor_id", options_from_collection_for_select(ReferringDoctor.all, "id", "name"), { :include_blank => '-- Select One --', :class => "form-control", :required => true  } %>
            </div>
            <div class="form-group">
              <label for="technition_id">Technition</label>
      
        
              <%= select_tag "technition_id", options_from_collection_for_select(User.technitions, "id", "name"), { :include_blank => '-- Select One --', :class => "form-control", :required => true  }  %>
            
          
            </div>
            <div class="form-group">
              <label for="note">Doctor</label>
              <%= select_tag "doctor_id", options_from_collection_for_select(User.doctors, "id", "name"), { :include_blank => '-- Select One --', :class => "form-control", :required => true  }  %>
            </div>
            <div class="form-group">
            <label for="discount">Discount</label>
           
              <input type="number" value="0.0" name="discount" class="form-control"/>
   
          </div>
            <input hidden name="patient_id" value="<%=@patient.id%>"/>
          <div class="field_wrapper">
            <div class="row" >
              <div class="col-6">
                <label for="note">
                  <strong>Items</strong>
                </label>
              </div>
              <div class="col-6 justify-content-end" style="text-align:end;">
                <a  class="add_button btn btn-success" style="padding:0px;padding-top:0.3rem;border-radius:50%;height:40px;width:40px;color:white;">
                  <i class="material-icons">add</i>
                </a>
              </div>
            </div>
            <div>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <input  type="submit" class="btn btn-success"/>
        </div>
      <%end %>
    </div>
  </div>
</div>
</div>

<script type="text/javascript">
function test(item){
     console.log(item.id);
     var id = item.id.substring(6)
     console.log(id);
  
     $.ajax({
    type:"GET",
    url:"/items/"+item.value,
    dataType:"json",
  
  
    success:function(result){
  	 console.log(result);
      $('#p'+id).val(result.price)
  
    },
    error: function(er){
  	  console.log(er);
  
    }
  })
  
  
  
   }
  $(document).ready(function(){
    
  
      var maxField = 30; //Input fields increment limitation
      var addButton = $('.add_button'); //Add button selector
      var wrapper = $('.field_wrapper'); //Input field wrapper
      var x = 1;
  
  
  
      //Once add button is clicked
      $(addButton).click(function(){
        // console.log("hi");
  
        var fieldHTML = '<div class="row" style="margin-top:8px;margin-right:5px;margin-left:5px;"><select required=true name="used_items_attributes[]" onchange="test(this)"  id="items_'+x+'" class="form-control col-8 itemSelect" required="required">'+
                        '<option value="">-- Select One --</option>'
                        <%Item.where(available: true).each do |item|%>
                        +'<option value="<%=item.id%>"><%=item.title%></option>'
                        <%end%>
                        +'</select>'
                        +'<input type=\'number\' id="p'+x+'" required=true class="form-control col-3" name="price[]" />'
                        + '<a class="col-1 remove_button" style="margin-top:2px;cursor: pointer; color: red;"><i class="material-icons">delete</i></a> </div>'
          //Check maximum number of input fields
          if(x < maxField){
              x++; //Increment field counter
              $(wrapper).append(fieldHTML); //Add field html
          }
      });
  
   
      $(wrapper).on('click', '.remove_button', function(e){
          e.preventDefault();
          $(this).parent('div').remove(); 
  
      });
  });
</script>
<script>
  function addCase(form) {
  
    console.log("adding case");
    console.log($("form").serializeArray());
  
    return false;
  
  }
</script>