config/routes.rb
Rails.application.routes.draw do
  resources :cases
  resources :referring_doctors
  resources :patients
  resources :items
  get 'users/index'
  post 'users/create'
  root 'cases#index'
  resources :user_roles
  resources :items
  resources :reports
  devise_for :users
  get 'user/:id', to: "users#toggle_activation", as: "toggle_activation"
  get 'items/activated_items', to: 'items#activated_items'
  post 'case/:id/end', to:'cases#end_case', as: "end_case"
  post 'case/:id/report', to:'cases#report_case', as: "reported_case"
  post 'case/:id/contact', to:'cases#contact_case', as: "contacted_case"
  put 'case/:id/items', to: 'cases#update_items', as: "update_case_items"
  put 'case/:id', to: 'cases#update', as: "update_case"


  get 'generate_reports', to: 'reports#generate_reports', as: "g_reports"
  get 'reports/result', to: 'reports#result', as: "reports_result"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
# == Schema Information
#
# Table name: items
#
#  id            :bigint           not null, primary key
#  title         :string
#  default_price :integer
#  available     :boolean
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#
class Item < ApplicationRecord
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authorize_controller
  def index
    @items = Item.all.order("id ASC")
  end

 
  def show
    @item = Item.find(params[:id])
    render :json => {price: @item.default_price}

  end

  def new
    @item = Item.new
  end

  def edit
  end

  def activated_items
    @items = Item.where(available: true)
    render :json => {price: @items}
  end

  def create
    @item = Item.new(items_params)
    respond_to do |format|
      if @item.save
        format.html { redirect_to items_url, notice: "Item was successfully created." }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  

  def destroy
    
    @item=Item.find(params[:id])
    @item.update(available: !(@item.available))
    respond_to do |format|
      format.html { redirect_to items_url, notice: "Item was successfully decativated." }
      format.json { head :no_content }
    end
  end
  def authorize_controller
    if !current_user.admin? 
      redirect_to root_path
    end
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    

    # Only allow a list of trusted parameters through.
    def items_params
      params.require(:item).permit(:title,:default_price, :available,:id, {})
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <label for="title">Title</label>
    <%= form.text_field :title ,{:class => 'form-control'}%>
  </div>

  <div class="form-group">
    <label for="default_price">Default Price</label>
    <%= form.number_field :default_price ,{:class => 'form-control'}%>
  </div>

  <div class="form-check">
    
    <%= form.check_box :available ,{:class => 'form-check-input', :id => 'available'} %>
    <label class="form-check-label" for="available">Available</label>
  </div>

  <div class="actions">
    <%= form.submit 'Create Item' , :class => 'mt-2 btn btn-primary'%>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>
<div class="col-lg-12">
        	<div class="panel panel-default">
            <div class="panel-heading">
                <div class="row">
                <h3 class="col-11">Items</h3>
                <button  class='btn btn-success' style="border-radius: 50%;line-height: 0px;color:white"><a style="color:white;" href=<%=new_item_path%>><i class="material-icons">add</i></a></button>
                
                </div>
            </div>
            <div class="panel-body">
<table class="table table-condensed" style="border-collapse:collapse;">

    <thead >
        <tr>
        <th>Title</th>
      <th>Default price</th>
      <th>Available</th>
      <th colspan="3"></th>

        </tr>
    </thead>

    <tbody class="table-striped table-hover"> 
      <% @items.each do |item| %>        
          

        
        <tr>
             <td><%= item.title %></td>
        <td><%= item.default_price %></td>
        <td>
          <% if item.available %>
              <p style="color:green;line-height:0px;">Yes</p>
          <% else %>
                <p style="color:red;">No</p>
            <%end %>
            </td>
        
        
        <% if item.available %>
          <td><%= link_to 'Deactivate', item_path(item.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% else %>
        
          <td><%= link_to 'Activate', item_path(item.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%end %>

        </tr>
  
        
      <% end %>
    </tbody>
    
</table>
            </div>
        
          </div> 
        
      </div>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @item.title %>
</p>

<p>
  <strong>Default price:</strong>
  <%= @item.default_price %>
</p>

<p>
  <strong>Available:</strong>
  <%= @item.available %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>